//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GenerarGruia.com.hermeco.chaosap {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsUtilidadesChaoSAPSoap", Namespace="http://tempuri.org/")]
    public partial class WsUtilidadesChaoSAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ImpresionEtiquetasOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarCorreoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsUtilidadesChaoSAP() {
            this.Url = global::GenerarGruia.Properties.Settings.Default.GenerarGruia_com_hermeco_chaosap_WsUtilidadesChaoSAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ImpresionEtiquetasCompletedEventHandler ImpresionEtiquetasCompleted;
        
        /// <remarks/>
        public event CargarArchivoCompletedEventHandler CargarArchivoCompleted;
        
        /// <remarks/>
        public event EnviarCorreoCompletedEventHandler EnviarCorreoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImpresionEtiquetas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImpresionEtiquetas(Etiqueta[] objEtiqueta, string strEtiqueta, string strMaquina, string strTipoImpresion) {
            object[] results = this.Invoke("ImpresionEtiquetas", new object[] {
                        objEtiqueta,
                        strEtiqueta,
                        strMaquina,
                        strTipoImpresion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImpresionEtiquetasAsync(Etiqueta[] objEtiqueta, string strEtiqueta, string strMaquina, string strTipoImpresion) {
            this.ImpresionEtiquetasAsync(objEtiqueta, strEtiqueta, strMaquina, strTipoImpresion, null);
        }
        
        /// <remarks/>
        public void ImpresionEtiquetasAsync(Etiqueta[] objEtiqueta, string strEtiqueta, string strMaquina, string strTipoImpresion, object userState) {
            if ((this.ImpresionEtiquetasOperationCompleted == null)) {
                this.ImpresionEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImpresionEtiquetasOperationCompleted);
            }
            this.InvokeAsync("ImpresionEtiquetas", new object[] {
                        objEtiqueta,
                        strEtiqueta,
                        strMaquina,
                        strTipoImpresion}, this.ImpresionEtiquetasOperationCompleted, userState);
        }
        
        private void OnImpresionEtiquetasOperationCompleted(object arg) {
            if ((this.ImpresionEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImpresionEtiquetasCompleted(this, new ImpresionEtiquetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarArchivo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargarArchivo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file, string filename) {
            object[] results = this.Invoke("CargarArchivo", new object[] {
                        file,
                        filename});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargarArchivoAsync(byte[] file, string filename) {
            this.CargarArchivoAsync(file, filename, null);
        }
        
        /// <remarks/>
        public void CargarArchivoAsync(byte[] file, string filename, object userState) {
            if ((this.CargarArchivoOperationCompleted == null)) {
                this.CargarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarArchivoOperationCompleted);
            }
            this.InvokeAsync("CargarArchivo", new object[] {
                        file,
                        filename}, this.CargarArchivoOperationCompleted, userState);
        }
        
        private void OnCargarArchivoOperationCompleted(object arg) {
            if ((this.CargarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarArchivoCompleted(this, new CargarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EnviarCorreo(string strEmialOrigen, string[] ArrEmailDestino, string[] ArrEmailCopia, string strAsunto, string strBody, bool blnBodyHtml, string[] parametros, string[] valores, string strAdjunto) {
            object[] results = this.Invoke("EnviarCorreo", new object[] {
                        strEmialOrigen,
                        ArrEmailDestino,
                        ArrEmailCopia,
                        strAsunto,
                        strBody,
                        blnBodyHtml,
                        parametros,
                        valores,
                        strAdjunto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarCorreoAsync(string strEmialOrigen, string[] ArrEmailDestino, string[] ArrEmailCopia, string strAsunto, string strBody, bool blnBodyHtml, string[] parametros, string[] valores, string strAdjunto) {
            this.EnviarCorreoAsync(strEmialOrigen, ArrEmailDestino, ArrEmailCopia, strAsunto, strBody, blnBodyHtml, parametros, valores, strAdjunto, null);
        }
        
        /// <remarks/>
        public void EnviarCorreoAsync(string strEmialOrigen, string[] ArrEmailDestino, string[] ArrEmailCopia, string strAsunto, string strBody, bool blnBodyHtml, string[] parametros, string[] valores, string strAdjunto, object userState) {
            if ((this.EnviarCorreoOperationCompleted == null)) {
                this.EnviarCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarCorreoOperationCompleted);
            }
            this.InvokeAsync("EnviarCorreo", new object[] {
                        strEmialOrigen,
                        ArrEmailDestino,
                        ArrEmailCopia,
                        strAsunto,
                        strBody,
                        blnBodyHtml,
                        parametros,
                        valores,
                        strAdjunto}, this.EnviarCorreoOperationCompleted, userState);
        }
        
        private void OnEnviarCorreoOperationCompleted(object arg) {
            if ((this.EnviarCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCorreoCompleted(this, new EnviarCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/clsEtiqueta.xsd")]
    public partial class Etiqueta {
        
        private Dato[] valorField;
        
        private long cantidadField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Valor")]
        public Dato[] Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <comentarios/>
        public long Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/clsEtiqueta.xsd")]
    public partial class Dato {
        
        private string valorField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ImpresionEtiquetasCompletedEventHandler(object sender, ImpresionEtiquetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImpresionEtiquetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImpresionEtiquetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CargarArchivoCompletedEventHandler(object sender, CargarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EnviarCorreoCompletedEventHandler(object sender, EnviarCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591